---
title: Tekne Blog
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
  posts:
    title: Posts
    output: true
    author: author
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: authors
  values:
    layout: author
email: tekne.blog@gmail.com
description: Tekne üyelerinin bir zeminde buluştuğu yer.
baseurl: 
url: tekneblog.github.io
theme: minima
plugins:
- jekyll-feed
header_pages:
- index.html
- about.html
- staff.html
- kategoriler.html
